import json
import shutil
import tempfile
import unittest
from pathlib import Path

from ihc import aesthetics, docs

from fixture_helpers import make_config, make_nixos_tmp

REGISTRY = """{ lib, ... }:

let
  mk =
    { name, image, artist, accentColor, polarity ? "dark" }:
    { inherit name image artist accentColor polarity; };
in
{
  profileName = "alpha";

  profiles = {
    alpha = mk {
      name = "Alpha Scene";
      image = "alpha.png";
      artist = "Anon";
      accentColor = "base0D";
      polarity = "dark";
    };

    beta = mk {
      name = "Beta Scene";
      image = "gone.png";
      artist = "Anon";
      accentColor = "base09";
      polarity = "light";
    };

    # gamma never got the accent/polarity treatment
    gamma = {
      name = "Gamma Scene";
      image = "gamma.png";
      artist = "Anon";
    };
  };
}
"""

GENERATED = """# generated by the theming engine
background #3C1F3E
foreground #ffdbb4
color1 #ff00ff
cursor rgb(60, 31, 62)
shadow #000000
font_family JetBrains Mono
"""


class PaletteTests(unittest.TestCase):
    def setUp(self):
        self.tmp = make_nixos_tmp()
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        self.cfg = make_config(self.tmp)
        self.gen = Path(tempfile.mkdtemp(prefix="ihc-gen-"))
        self.addCleanup(shutil.rmtree, self.gen, ignore_errors=True)
        p = self.gen / "home-files/.config/stylix"
        p.mkdir(parents=True)
        (p / "palette.json").write_text(json.dumps({"base00": "3C1F3E", "base05": "#FFDBB4", "scheme": "Example"}))

    def test_palette_json_in_a_generation_is_normalised(self):
        pal = aesthetics.palette(self.cfg, self.gen)
        self.assertEqual(pal, {"base00": "#3c1f3e", "base05": "#ffdbb4"})


class ScanSurfaceTests(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="ihc-scan-"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        self.file = self.tmp / "kitty.conf"
        self.file.write_text(GENERATED)

    def test_css_id_selectors_are_not_colours(self):
        css = self.tmp / "style.css"
        css.write_text("#backlight {\n  color: #3c1f3e;\n}\n#clock { color: #ffdbb4; }\n#face { color: #abc; }\n")
        s = aesthetics.scan_surface(css, {"base00": "#3c1f3e", "base05": "#ffdbb4"})
        self.assertEqual(s["total"], 3)
        self.assertEqual(s["in_palette"], 2)
        self.assertEqual([f["colour"] for f in s["foreign"]], ["#aabbcc"])

    def test_counts_palette_foreign_neutral_and_fonts(self):
        s = aesthetics.scan_surface(self.file, {"base00": "#3c1f3e", "base05": "#ffdbb4"})
        self.assertEqual(s["total"], 5)
        self.assertEqual(s["in_palette"], 3)
        self.assertEqual(s["neutral"], 1)
        self.assertEqual(s["foreign_unique"], 1)
        self.assertEqual(s["foreign"][0]["colour"], "#ff00ff")
        self.assertEqual(s["foreign"][0]["lines"], [4])
        self.assertIn("JetBrains Mono", s["fonts"])

    def test_missing_file_is_none(self):
        self.assertIsNone(aesthetics.scan_surface(self.tmp / "nope.conf", {}))

    def test_binary_file_is_none(self):
        b = self.tmp / "blob.bin"
        b.write_bytes(b"\x00\x01\x02#ff00ff")
        self.assertIsNone(aesthetics.scan_surface(b, {}))


class ProfileRegistryTests(unittest.TestCase):
    def setUp(self):
        self.root = Path(tempfile.mkdtemp(prefix="ihc-registry-"))
        self.addCleanup(shutil.rmtree, self.root, ignore_errors=True)
        (self.root / "registry.nix").write_text(REGISTRY)
        (self.root / "alpha.png").write_bytes(b"x")
        (self.root / "gamma.png").write_bytes(b"x")
        self.profiles = aesthetics.profiles([self.root / "registry.nix"], [self.root])

    def test_every_profile_is_found_with_its_fields(self):
        by_name = {p["name"]: p for p in self.profiles}
        self.assertEqual(set(by_name), {"alpha", "beta", "gamma"})
        self.assertEqual(by_name["alpha"]["image"], "alpha.png")
        self.assertEqual(by_name["alpha"]["title"], "Alpha Scene")
        self.assertEqual(by_name["alpha"]["accentColor"], "base0D")
        self.assertEqual(by_name["beta"]["polarity"], "light")

    def test_current_profile_comes_from_profile_name(self):
        self.assertEqual([p["name"] for p in self.profiles if p["current"]], ["alpha"])

    def test_incomplete_profile_lists_the_fields_the_others_have(self):
        gamma = next(p for p in self.profiles if p["name"] == "gamma")
        self.assertEqual(gamma["missing_fields"], ["accentColor", "polarity"])
        for name in ("alpha", "beta"):
            self.assertEqual(next(p for p in self.profiles if p["name"] == name)["missing_fields"], [])

    def test_missing_image_is_flagged(self):
        self.assertEqual([p["name"] for p in self.profiles if p["image_exists"] is False], ["beta"])

    def test_line_numbers_point_at_the_profile(self):
        alpha = next(p for p in self.profiles if p["name"] == "alpha")
        self.assertEqual(REGISTRY.splitlines()[alpha["line"] - 1].strip(), "alpha = mk {")


class SurfaceTableTests(unittest.TestCase):
    def test_every_entry_has_a_label_and_home_relative_paths(self):
        self.assertTrue(aesthetics.SURFACES)
        for key, s in aesthetics.SURFACES.items():
            self.assertTrue(s["label"], key)
            self.assertTrue(s["paths"], key)
            self.assertIn("stylix", s)
            for rel in s["paths"]:
                self.assertFalse(rel.startswith(("/", "~")), "%s: %s is not relative to $HOME" % (key, rel))

    def test_known_surfaces_are_covered(self):
        for key in ("kitty", "waybar", "hyprland", "rofi", "mako", "gtk", "qt", "firefox", "cursor", "fonts", "tmux", "zsh"):
            self.assertIn(key, aesthetics.SURFACES)


class AestheticSurfacesDocTests(unittest.TestCase):
    def test_parses_bullets_and_ignores_other_sections(self):
        with tempfile.TemporaryDirectory() as tmp:
            Path(tmp, "MAINTENANCE.md").write_text(
                "# M\n\n## Guarded units\n\n- audio-daemon.service\n\n## Aesthetic surfaces\n\n"
                "- example bar: .config/example-bar/style.css\n- `example menu`: `~/.config/example-menu/theme.rasi`\n\n"
                "## Queue\n\n- [ ] (risk: low) x\n")
            self.assertEqual(
                docs.aesthetic_surfaces(Path(tmp)),
                {"example bar": ".config/example-bar/style.css", "example menu": ".config/example-menu/theme.rasi"},
            )

    def test_missing_file_is_empty(self):
        self.assertEqual(docs.aesthetic_surfaces(Path("/nonexistent")), {})


if __name__ == "__main__":
    unittest.main()


class CurrentNameTests(unittest.TestCase):
    def test_ignores_regex_looking_strings(self):
        import tempfile
        from pathlib import Path
        from ihc import aesthetics
        with tempfile.TemporaryDirectory() as d:
            decoy = Path(d) / "a.nix"; decoy.write_text('x = "profileName = \\"(?<name>[^,]+)\\"";\n')
            real = Path(d) / "b.nix"; real.write_text('profileName = "sunset";\n')
            self.assertEqual(aesthetics.current_name([decoy, real]), "sunset")
